@startuml
'https://plantuml.com/class-diagram

class ToDoList {
    + main()
    + start()
}

class ToDo {
    - Title: String
    - Items: String[]
}

class ToDoListController {
    - textDisplay: TextField

    + addItemButtonClicked()
    + removeItemButtonClicked()
    + editItemDescriptionButtonClicked()
    + editItemDueDateButtonClicked()
    + markItemCompleteButtonClicked()
    + displayAllItemsButtonClicked()
    + displayIncompletionsButtonClicked()
    + displayCompletionsButtonClicked()
    + saveItemsButtonClicked()
    + saveAllItemsButtonClicked()
    + loadSingleToDoListButtonClicked()
    + loadMultToDoListButtonClicked()

    + addItem()
    + removeItem()
    + editItemDescription()
    + editItemDueDate()
    + markItemComplete()
    + displayAllItems()
    + displayIncompletions()
    + displayCompletions()
    + saveItems()
    + saveAllItems()
    + loadSingleToDoList()
    + loadMultToDoList()
}

javafx.Application <|-- ToDoList

ToDoList - ToDoListController

ToDoListController *-- ToDo

@enduml