@startuml
'https://plantuml.com/class-diagram

class ToDoList {
    + main()
    + start()
}

class ToDo {
    - Title: String
    - Items: String[]
}

class ToDoListController {
    t: ToDoItem
    list: List<ToDoItem>
    - textOutput: TextField
    - textName: TextField
    - textDesc: TextField
    - textDate: TextField
    - textComplete: TextField

    + addItemButtonClicked()
    + removeItemButtonClicked()
    + editDescriptionButtonClicked()
    + editDueDateButtonClicked()
    + markItemCompleteButtonClicked()
    + displayAllItemsButtonClicked()
    + displayIncompleteButtonClicked()
    + displayCompletionsButtonClicked()
    + saveItemsButtonClicked()
    + loadListButtonClicked()
    + clearListButtonClicked()

    + addItem()
    + removeItem()
    + clearList()
    + editDescription()
    + editDueDate()
    + markItemComplete()
    + displayAllItems()
    + displayIncomplete()
    + displayCompletions()
    + saveItems()
    + loadList()
    + getText(TextField t)
    + setTextOutput(String text)
    + clearText(TextField t)
    +
}

javafx.Application <|-- ToDoList

ToDoList - ToDoListController

ToDoListController *-- ToDo

@enduml